# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visio.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QApplication,QVBoxLayout,QFrame,QHBoxLayout,QWidget,QLineEdit,QComboBox,QGridLayout
import  sys,re,os

class NodeWidget(QWidget):
    def __init__(self,ID=0,parent=None ):
        super(NodeWidget, self).__init__(parent)
        laytout = QHBoxLayout()
        self.input_id = QLineEdit(str(ID))
        self.input_id.setFixedWidth(30)
        self.input_text = QLineEdit("")
        self.input_text.setFixedHeight(20)
        self.input_text.setFixedWidth(400)
        self.input_type = QComboBox()
        self.input_type.addItem('开始/结束')
        self.input_type.addItem('流程')
        self.input_type.addItem('判定')
        self.input_type.addItem('None')
        self.input_type.setFixedWidth(80)
        self.input_x = QLineEdit("0")
        self.input_x.setFixedWidth(30)
        self.input_y = QLineEdit("0")
        self.input_y.setFixedWidth(30)
        self.input_link1 = QLineEdit("")
        self.input_link1.setFixedWidth(30)
        self.input_link2 = QLineEdit("")
        self.input_link2.setFixedWidth(30)

        laytout.addWidget(self.input_id)
        laytout.addWidget(self.input_text)
        laytout.addWidget(self.input_type)
        laytout.addWidget(self.input_x)
        laytout.addWidget(self.input_y)
        laytout.addWidget(self.input_link1)
        laytout.addWidget(self.input_link2)
        laytout.addStretch()
        laytout.setContentsMargins(0,0,0,0)
        self.setLayout(laytout)
        self.show()
        self.data = [ ]

class Ui_Form(object):
    def setupUi(self, Form):
        self.form = Form
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 991, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(2, 0, 5, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label01 = QtWidgets.QLabel(self.widget)
        self.label01.setObjectName("label01")
        self.horizontalLayout.addWidget(self.label01)
        self.input_nodenums = QtWidgets.QLineEdit(self.widget)
        self.input_nodenums.setObjectName("input_nodenums")
        self.horizontalLayout.addWidget(self.input_nodenums)
        self.label02 = QtWidgets.QLabel(self.widget)
        self.label02.setObjectName("label02")
        self.horizontalLayout.addWidget(self.label02)
        self.input_filename = QtWidgets.QLineEdit(self.widget)
        self.input_filename.setObjectName("input_filename")
        self.horizontalLayout.addWidget(self.input_filename)
        self.label03 = QtWidgets.QLabel(self.widget)
        self.label03.setObjectName("label03")
        self.horizontalLayout.addWidget(self.label03)
        self.input_sheetname = QtWidgets.QLineEdit(self.widget)
        self.input_sheetname.setObjectName("input_sheetname")
        self.horizontalLayout.addWidget(self.input_sheetname)
        self.addnode_btn = QtWidgets.QPushButton(self.widget)
        self.addnode_btn.setObjectName("addnode_btn")
        self.horizontalLayout.addWidget(self.addnode_btn)
        self.start_btn = QtWidgets.QPushButton(self.widget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.layout = QVBoxLayout(self.widget)

        self.frame = QFrame(self.form)
        self.frame.setMinimumHeight(400)
        self.frame.setMaximumWidth(800)
        self.frame.setMaximumWidth(1000)
        self.frame.setMaximumHeight(2000)
        self.frame.show()

        self.node_num = 0
        self.addnode_btn.clicked.connect(self.add_node)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "自动画流程图工具"))
        self.label01.setText(_translate("Form", "节点个数:"))
        self.label02.setText(_translate("Form", "visio文件名:"))
        self.label03.setText(_translate("Form", "sheetname:"))
        self.addnode_btn.setText(_translate("Form", "添加节点"))
        self.start_btn.setText(_translate("Form", "开始画图"))

    def  add_node(self):
        bt = NodeWidget( self.node_num,self.frame)
        bt.move(0,80+30*self.node_num)
        print("add node ",self.node_num )
        self.node_num += 1

if __name__ == '__main__':
    app = QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    test = Ui_Form()
    test.setupUi(widget)
    widget.show()
    sys.exit(app.exec())
